version: '3.8'

services:
  db:
    image: postgres:13
    container_name: tawssil_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tawssil_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tawssil_db
    restart: always

  web:
    build: .
    container_name: tawssil_backend
    command: gunicorn tawssil_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/tawssil_backend/static
      - media_volume:/app/tawssil_backend/media
      - ./:/app
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:1.21
    container_name: tawssil_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
