# Generated by Django 5.2 on 2025-04-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('methode', models.CharField(choices=[('Espum', 'Espèces'), ('Cash', 'Cash'), ('App', 'Application')], max_length=10)),
                ('statut', models.CharField(choices=[('En Attente', 'En Attente'), ('Confirme', 'Confirmé'), ('Echoue', 'Échoué')], default='En Attente', max_length=15)),
                ('recu', models.CharField(blank=True, max_length=255, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.commande')),
            ],
        ),
    ]
