# Generated by Django 5.2 on 2025-06-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='recu',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/recus/'),
        ),
    ]
