# Generated by Django 5.2 on 2025-06-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_alter_paiement_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('Espum', 'Espèces'), ('App', 'Application')], max_length=10),
        ),
    ]
