# Generated by Django 5.2 on 2025-05-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.livreur')),
            ],
        ),
    ]
