# Generated by Django 5.2 on 2025-05-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.chauffeur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.client'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.livreur'),
        ),
    ]
