# Generated by Django 5.2 on 2025-05-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('Moto', 'Moto'), ('Taxi', 'Taxi'), ('Camion', 'Camion')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.chauffeur')),
            ],
        ),
    ]
