# Generated by Django 5.2 on 2025-04-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id_trajet', models.AutoField(primary_key=True, serialize=False)),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Termine', 'Terminé')], default='En attente', max_length=15)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('Moto', 'Moto'), ('Taxi', 'Taxi'), ('Camion', 'Camion')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.chauffeur')),
            ],
        ),
    ]
