# Generated by Django 5.2 on 2025-04-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id_colis', models.AutoField(primary_key=True, serialize=False)),
                ('poids', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En Transit', 'En Transit'), ('Livre', 'Livré')], default='En attente', max_length=15)),
                ('montant', models.FloatField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_recus', to='utilisateurs.client')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_expedies', to='utilisateurs.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('methode_paiement', models.CharField(choices=[('Cash', 'Cash'), ('App', 'Application')], max_length=10)),
                ('montant', models.FloatField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptee', 'Acceptée'), ('En cours', 'En cours'), ('Terminee', 'Terminée'), ('Annulee', 'Annulée')], default='En attente', max_length=15)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('recu_transaction', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id_voyage', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('poids_disponible', models.FloatField()),
                ('tarif_transport', models.FloatField()),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.client')),
            ],
        ),
    ]
