# Generated by Django 5.2 on 2025-05-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id_colis', models.AutoField(primary_key=True, serialize=False)),
                ('poids', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En Transit', 'En Transit'), ('Livre', 'Livré')], default='En attente', max_length=15)),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('adresse_livraison', models.TextField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('En préparation', 'En préparation'), ('En livraison', 'En livraison'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('code_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='commandes/qrcodes')),
                ('instructions_speciales', models.TextField(blank=True, null=True)),
                ('date_livraison_estimee', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id_voyage', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('poids_disponible', models.FloatField()),
                ('tarif_transport', models.FloatField()),
            ],
        ),
    ]
