# Generated by Django 5.2 on 2025-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('En route', 'En route'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='En attente', max_length=20),
        ),
    ]
