# Generated by Django 5.2 on 2025-06-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_voyage_statut'),
        ('utilisateurs', '0003_utilisateur_is_staff_alter_utilisateur_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='utilisateurs.chauffeur'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='rating',
            field=models.FloatField(blank=True, help_text='تقييم الرحلة من 1 إلى 5', null=True),
        ),
    ]
