# Generated by Django 5.2 on 2025-04-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type_utilisateur', models.CharField(choices=[('Client', 'Client'), ('Livreur', 'Livreur'), ('Chauffeur', 'Chauffeur'), ('Administrateur', 'Administrateur')], max_length=15)),
                ('photo_cart', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauffeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('note_moyenne', models.FloatField(blank=True, default=0, null=True)),
                ('disponibilite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id_livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('type_transport', models.CharField(blank=True, choices=[('Moto', 'Moto'), ('Camion', 'Camion')], max_length=10, null=True)),
                ('disponibilite', models.BooleanField(default=False)),
                ('zone_couverture', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
