# Generated by Django 5.2 on 2025-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='type',
            field=models.CharField(default='EMAIL', help_text='نوع الرمز: EMAIL أو SMS', max_length=10),
        ),
    ]
