# Generated by Django 5.2 on 2025-04-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='nom_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='matricule_voiture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_assurance',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/papiers/assurance'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/papiers/carte_grise'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_carte_municipale',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/papiers/municipale'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/permis'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_vignette',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/papiers/vignette'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_voiture',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/photos/voitures'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='type_voiture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='id_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_admin', serialize=False, to='utilisateurs.utilisateur'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='id_chauffeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_chauffeur', serialize=False, to='utilisateurs.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_cart',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos'),
        ),
    ]
