# Generated by Django 5.2 on 2025-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20250517_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='type',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Client', 'Client'), ('Livreur', 'Livreur'), ('Chauffeur', 'Chauffeur'), ('Administrateur', 'Administrateur'), ('Fournisseur', 'Fournisseur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
