# Generated by Django 5.2 on 2025-04-23 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_administrateur_nom_admin_chauffeur_matricule_voiture_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='utilisateur',
        #     name='date_joined',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
