# Generated by Django 5.2 on 2025-04-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_date_joined_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE django_migrations SET applied = NOW() WHERE app = \'utilisateurs\' AND name = \'0003_utilisateur_date_joined_utilisateur_is_active_and_more\''
        ),
    ]
