# Generated by Django 5.2 on 2025-05-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_otpcode_type_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='type',
            field=models.CharField(default='EMAIL', help_text='نوع الرمز: EMAIL أو SMS', max_length=10),
        ),
    ]
