# Generated by Django 5.2 on 2025-04-29 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_auto_20250423_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
