# Generated by Django 5.2 on 2025-05-17 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_otpcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='registration_data',
            field=models.JSONField(blank=True, help_text='بيانات التسجيل المؤقتة للمستخدم', null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
