# Generated by Django 5.2 on 2025-04-29 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_manual_add_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='matricule_voiture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='note_moyenne',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_assurance',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/papiers/assurance'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/papiers/carte_grise'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_carte_municipale',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/papiers/municipale'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/permis'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_vignette',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/papiers/vignette'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='photo_voiture',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/photos/voitures'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='id_livreur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_livreur', serialize=False, to='utilisateurs.utilisateur'),
        ),
    ]
