name: Backend CI/CD

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'tawssil_backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'tawssil_backend/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tawssil_backend

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tawssil_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tawssil_test
          DJANGO_SECRET_KEY: 'django-insecure-for-testing-only'
          DEBUG: 'True'
        run: python manage.py migrate
      
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tawssil_test
          DJANGO_SECRET_KEY: 'django-insecure-for-testing-only'
          DEBUG: 'True'
        run: python manage.py test
      
      - name: Run Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build_and_push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tawssil-backend:latest

  deploy:
    name: Deploy to Production
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker system prune -af 