name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.5.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd tawssil_frontend
        flutter pub get
        
    - name: Analyze code
      run: |
        cd tawssil_frontend
        flutter analyze
        
    - name: Run tests
      run: |
        cd tawssil_frontend
        flutter test
        
    - name: Build APK
      run: |
        cd tawssil_frontend
        flutter build apk --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: tawssil_frontend/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Setup PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo service postgresql start
        sudo -u postgres psql -c "CREATE DATABASE tawssil;"
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'Ab@2024';"
        
    - name: Run database tests
      run: |
        cd tawssil_frontend
        dart lib/test_connection.dart 